site_name: pwiki docs
site_url: https://fastily.github.io/pwiki/

theme:
  name: material
  palette:
    scheme: slate

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences